# Generated by Django 5.2.10 on 2026-02-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mess',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
