# Generated by Django 5.2.10 on 2026-02-04 06:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messes', '0003_mess_is_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner')], max_length=10)),
                ('items', models.TextField(help_text='Comma separated items')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_menus', to='messes.mess')),
            ],
            options={
                'ordering': ['day', 'meal_type'],
                'unique_together': {('mess', 'day', 'meal_type')},
            },
        ),
    ]
