# Generated by Django 5.2.10 on 2026-02-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messes', '0004_weeklymenu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['day', 'meal_type']},
        ),
        migrations.AddField(
            model_name='menu',
            name='day',
            field=models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], default='MONDAY', max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='WeeklyMenu',
        ),
    ]
