# Generated by Django 5.2.10 on 2026-02-04 15:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messes', '0005_alter_menu_options_menu_day_delete_weeklymenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mess',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
