# Generated by Django 5.2.10 on 2026-02-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messes", "0009_alter_messplan_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanMenuItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day", models.CharField(choices=[("MONDAY", "Monday"), ("TUESDAY", "Tuesday"), ("WEDNESDAY", "Wednesday"), ("THURSDAY", "Thursday"), ("FRIDAY", "Friday"), ("SATURDAY", "Saturday"), ("SUNDAY", "Sunday")], max_length=10)),
                ("meal_type", models.CharField(choices=[("BREAKFAST", "Breakfast"), ("LUNCH", "Lunch"), ("DINNER", "Dinner")], max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="plan_items", to="messes.messplan")),
            ],
            options={
                "ordering": ["day", "meal_type", "name"],
            },
        ),
    ]
