# Generated by Django 5.2.10 on 2026-02-15 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messes', '0007_messplan'),
    ]

    operations = []
