# Generated by Django 6.0 on 2026-01-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_budget', models.IntegerField()),
                ('max_distance_km', models.FloatField()),
                ('food_type', models.CharField(choices=[('VEG', 'Veg'), ('NON_VEG', 'Non-Veg'), ('BOTH', 'Both')], max_length=10)),
                ('meals_required', models.CharField(max_length=50)),
            ],
        ),
    ]
